### ISSUE TITLE
Try out the mapfield innovation

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#845] opened 2016-04-26 15:04 UTC
https://github.com/elmsln/innovations/pull/25

we've got our first pull request for a new innovation from wildwest (actually it's by @aitala)

@proconnor15 I want you and @mmilutinovic1313 to work together on this to come up with the best workflow for trying out new innovations in local vagrant instances. This process will need documented as well as coming up with a process by which you try these out and then we talk through integrating it into the full package / ways we can leverage automation further to make it even easier.

The innovations currently stamp out as install profiles which could be hooked up to elmsln if we had a script to do so (don't currently). Could also do a mode where people can select an item in the UI and pull it in from github directly though this is obviously more dangerous (potentially) so I'd want it only to work in vagrant.

It comes with a drush recipe method as well so here's the steps to getting this working so you have a foundation to go off of:
- check out the pull request for the innovation in question (could also do https://github.com/ELMSLNInnovationBot/wildwest and pick the branch in question, that's probably easier)
- clone this to /var/www/elmsln/config/shared/drupal-7.x/modules so that it's all in scope of the rest of the systems
- make an innovate space
- enable the install profile as a module (this should work though I know it's weird)

If it does work that way, then there's a drush recipe that comes with it in which case look into how to run a custom recipe against a site and it'll basically run all the commands to make the site the same as what eric had in his VM. It takes longer to execute but might be a more automatable workflow

**Comment by mmilutinovic1313** [comment] 2016-04-29 15:31
@btopro - so we got through the first 3 steps and are making an innovate space. @proconnor15 had a previous innovate space in his sing100 course, but when he went to access the modules page -- a giant error message appeared ( @proconnor15  will attach screenshots below). Same occurred when trying to clear caches. Not sure if this is caused by the us creating new services while trying to access modules / cache clear, but we were curious if you could point us in the right direction in removing these error messages.

**Comment by proconnor15** [comment] 2016-04-29 15:32
<img width="1196" alt="screen shot 2016-04-29 at 11 29 36 am" src="https://cloud.githubusercontent.com/assets/16597608/14921014/efdf6438-0dfd-11e6-9e6e-ef65e7df3f44.png">
<img width="1428" alt="screen shot 2016-04-29 at 11 29 58 am" src="https://cloud.githubusercontent.com/assets/16597608/14921022/f96003a0-0dfd-11e6-9d7e-6bcc52a598ea.png">

**Comment by mmilutinovic1313** [comment] 2016-04-29 15:51
Additionally the course builder may have stalled out as we are getting this message when trying to access the service:

```
Array
(
    [type] => 1
    [message] => Call to undefined function user_access()
    [file] => /var/www/elmsln/core/dslmcode/cores/drupal-7/modules/system/system.module
    [line] => 1966
)

```
 @proconnor15 's status indicator says "waiting for server" -- mine doesn't give me a status indicator

**Comment by mmilutinovic1313** [comment] 2016-04-29 16:16
@heyMP - do you have any clue what might be going on here as well?

**Comment by mmilutinovic1313** [comment] 2016-04-29 16:45
UPDATE: We tried a few different iterations of installation order and got the same error messages as above.

**Comment by btopro** [comment] 2016-04-29 21:13
@mmilutinovic1313 did u guys try the drush recipe method? Sounds like user module might not be enabled which sounds borderline impossible but apparently it is ;)

**Comment by mmilutinovic1313** [comment] 2016-05-02 02:28
@btopro That we did not haha. I thought that the instructions were for how to get the recipe to work. So you're saying if we run the drecipe we those are the steps that it will run? Will try this later tonight / tomorrow!

**Comment by mmilutinovic1313** [comment] 2016-05-06 19:12
Tried the drush recipe method as well. What seems to be happening is that when wildwest is cloned into the directory everything is fine and you can do a drush cc all and access modules. When you switch branches and download from origin ema13-mapbyaddressfield the innovators folder seems to cause these errors on Cache Clear and Modules to appear.

**Comment by mmilutinovic1313** [comment] 2016-05-06 19:18
Here is the path I put wildwest in: `/home/vagrant/elmsln/config/shared/drupal-7.x/modules/wildwest`

**Comment by btopro** [comment] 2016-05-06 19:30
try this; kill everything in the .install file for the install profile. It's going to want to create user accounts that (potentially) already exist; see if this helps at all

**Comment by mmilutinovic1313** [comment] 2016-05-06 19:32
Okay will do - but should it be causing the error even before I run the `drush en` against it? I thought that was a bit strange.

**Comment by btopro** [comment] 2016-05-06 19:34
ya that's weird then...

**Comment by mmilutinovic1313** [comment] 2016-05-06 19:39
Once this processes here is a walkthrough: https://www.youtube.com/watch?v=jNj87XJySYs&feature=youtu.be

**Comment by btopro** [comment] 2016-05-06 19:47
try this

check that stuff out. Then delete everything EXCEPT the features directory -- https://github.com/ELMSLNInnovationBot/wildwest/tree/ema13-mapbyaddressfield/innovators/ema13/7.x/mapbyaddressfield/modules/features

Also could try just deleting the install profile stuff at the high level (and theme) and that should take care of it.

**Comment by mmilutinovic1313** [comment] 2016-05-09 14:06
Things I've learned Update: 

1. When I deleted everything except for features, everything crashed still.
2. Deleting features removed the errors and I was able to do a Cache Clear
3. After the features folder is deleted the `drush @target en` command only produces a "I can't find this module on D.O. error"

**Comment by mmilutinovic1313** [comment] 2016-05-10 10:51
I posted an issue on D.O. about the long feature name (https://www.drupal.org/node/2721833) and they put in a patch that will save 19 characters, but we should probably look for other sanitation methods if possible. I'm going to close this issue for now while I look for solutions.

**Comment by mmilutinovic1313** [comment] 2016-05-10 10:51
Actually -- I cannot as I do not have closing permissions :P . But this is marked to be closed

**Closed** 2016-05-10 14:24 UTC
Labels: enhancement, innovate/ulmus
