### ISSUE TITLE
Adding Students to Offerings/Classes

### ISSUE THREAD

**Issue by scottholmes** [elmsln/elmsln#766] opened 2016-03-20 07:44 UTC
I have been unable to find out how to attach a student to a course.  If I'm not mistaken the finest resolution of a course is an offering.  This would be the scheduled class complete with instructor and allocated resources.  I have added a person to the system with the role of student but I have been unable to associate this "person" with an offering.

**Comment by btopro** [comment] 2016-03-20 12:02
The data model in CIS goes:
Course
- Offering
  - Section

Offering would be like "fall 2016" kind of data point where section would be all the details associated with the course running (instructor, syllabus, resources it uses, *access strings*, etc). Right now, the access strings are the only automated way to get users attached to sections and involve a coded solution. An example backported from what we use is https://github.com/elmsln/elmsln-config-example/blob/master/shared/drupal-7.x/modules/cis_implementation_example/cis_example_lms_sync/cis_example_lms_sync.module

We are hashing out how best to do this in #550 and ideally would have 1 site manage this user brokering for the network; making the accounts globally and ensuring access is correct. Whether that happens in the CIS/online site or not is still open (though entry will most likely be in CIS)

**Comment by btopro** [comment] 2016-03-23 00:48
duplicate of #766

**Closed by btopro** 2016-03-23 00:48 UTC
Labels: duplicate, people / cpr
