### ISSUE TITLE
Ubuntu 18 handsfree installer

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/elmsln#2626] opened 2019-05-30 14:23 UTC
Hi all,

Is a handsfree installer for Ubuntu 18 on the roadmap for the future?

As a partly related question: At the moment, we're moving onto PHP7. Everything looks like it's working on a fresh copy of ELMS but is there anything we should be aware of? If you've had any issues at all of course.

**Comment by btopro** [comment] 2019-05-30 14:39
our Vagrant instance runs the Ubuntu 16 which is on php 7 so it should be fine (way faster, enjoy the speed bump). I'd also HIGHLY recommend getting HTTP2 setup. Here's some stuff that we put together recently for HAXiam's installer -- https://github.com/elmsln/HAXiam/blob/master/scripts/ubuntu18.04.sh#L33-L49

You'll see PHP FPM 7.2 on Ubuntu 18 as well as http2 and apache2 fcgi to handle php fpm config and some additional performance tweaks 

As for a handsfree ELMSLN installer for Ubuntu 18 we'd accept a patch to provide one that'd be great, it shuldn't be too different from the ubuntu 16 one

**Comment by btopro** [comment] 2019-07-12 02:26
@JackWillDavis this is a boilerplate by taking U16 and then adding in known working configurations from HAXcms as that supports U18. I think it'll work but I haven't tested.

**Comment by JackWillDavis** [comment] 2020-02-20 12:56
Hi @btopro 

I've just run a couple of tests and it looks like I can't install a fresh version of ELMSLN on Ubuntu 18 using the installer. Here's the server config:

AWS Lightsail
4GB RAM / 2 vCPUs / 80GB storage
Using a virtual domain name (edited my local /etc/hosts file)
Ubuntu 18.04

Looks like PHP isn't installed after the installer is run. Drush & Leafy aren't available either and it's just printing out the PHP code when navigating to the site.

![image](https://user-images.githubusercontent.com/2301874/74935384-0df28a00-53e0-11ea-877a-a3cb1bc793e1.png)

I ran these commands:

```
sudo git clone https://github.com/elmsln/elmsln.git /var/www/elmsln && cd /var/www/elmsln && sudo git checkout tags/0.12.0

sudo bash /var/www/elmsln/scripts/install/handsfree/ubuntu18/ubuntu18-install.sh [CODE] bc [MY DOMAIN] http [MY EMAIL] yes
```

**Comment by btopro** [comment] 2020-02-20 13:03
yea U18 is untested. It's just a clone of the U16 so the PHP / dependencies probably need fixed

**Comment by JackWillDavis** [comment] 2020-02-20 18:28
OK, the installer seems to be a bit happier but I'm running into an issue I can't seem to find any clues on.

It's got to the point where it's installing the authority tools, the first couple are fine:

![image](https://user-images.githubusercontent.com/2301874/74965928-ff22cc00-540d-11ea-876e-3b3efdcb102c.png)

When it's installing the API tool though, it throws a couple of deprecated warnings then freezes when it gets to enabling the `cis_service_restws` module.

Here's where it gets up to in the prompt:

![image](https://user-images.githubusercontent.com/2301874/74966075-4f019300-540e-11ea-97da-3956ff73390c.png)

It sits there indefinitely and there's no errors or warnings logged anywhere which is telling me what it's failing/stalling on.

You can see what changes I've made here: https://github.com/JackWillDavis/elmsln/commits/ubuntu18

If you or anyone else here has any ideas on it I'd appreciate a fresh pair of eyes, this is a lot further on through the installation than it's been getting so hoping I'm near the finish line!

**Comment by btopro** [comment] 2020-02-20 19:34
https://github.com/elmsln/elmsln/blob/master/scripts/install/elmsln-install.sh#L64-L90

this steps into the stacks directory and builds dynamically. So let's do this because honestly they aren't used by anyone....

Go into https://github.com/elmsln/elmsln/tree/master/core/dslmcode/stacks

and delete the following....

api
hub
inbox
lor
lq

should reduce the time spent during install for things you dont use anyway. Let's see if that helps

**Comment by JackWillDavis** [comment] 2020-02-20 20:02
Ah OK, I’ll do that, run it again and let you know. Thanks!

**Comment by btopro** [comment] 2020-02-20 20:16
Please do. I think for a V1 we need to cut the dead weight. Those ideas never went anywhere fully

**Comment by JackWillDavis** [comment] 2020-02-21 08:36
I'm running into the same issue I'm afraid, on the `@interact` authority tool this time. I've gone through and replaced `mcrypt` and `php-xml-parser` packages with the PHP7.2 compatible versions as I realised I left it out before.

Also removed those stack folders as well but its stalled again on drush enabling `cis_service_restws`.

**Comment by JackWillDavis** [comment] 2020-02-21 09:03
So I ran it again after it had already failed (knew it wouldn't complete but just to see) and this error about `elmsln_core_get_profile_key()` not being defined. I had a look through and I can see it *is* defined in the 0.12.0 branch but thought I would add it in, just in case it helps shed light on it.

![image](https://user-images.githubusercontent.com/2301874/75019579-063af000-5489-11ea-8eac-6c757d3c87f0.png)

**Comment by JackWillDavis** [comment] 2020-02-21 11:50
At this point in the installation, shouldn't drush be installed globally? If I cancel out at this point and try to run `drush version`, the drush command isn't recognised.

**Comment by btopro** [comment] 2020-02-21 14:26
should be. What version are you working off of? Master or another branch? I was messing w/ the drush install stuff in the 13x and es8 branches to try and get it working on Vagrant locally. We're in a clash of version capabilities. Some version of Drush works with D7 and D8 while using PHP7.2. Really need help in this area of untangling these and getting drush installed globally in a way that works w/ most up to date installs and php. I believe we're running a mod'ed verison of 13.x currently which has some work done to help support PHP 7 fresh installs (some issues were in views and other features things)

**Comment by JackWillDavis** [comment] 2020-02-21 14:37
Yeah I know Drush 8 works for both Drupal 7 and 8. I tried changing the composer dependency to drush 8 but didn't help in this case.

I think it's something to do with the `.bashrc` file. If I let the installer run, then try to run `drush version`, it says drush isn't a known command. If I then close the terminal and reopen, it shows me the correct drush version.

It seems that the `source .bashrc` command in the installer, which should refresh the export paths to drupal, doesn't work at the time. Not sure about the best way to go about it though.

At the moment, I'm working off the 0.12.0 branch as that was the last stable release (we're trying to get on a totally up-to-date stack).

**Comment by btopro** [comment] 2020-02-21 14:45
es8 and 13.x have some of these things in it... ugh..

https://github.com/elmsln/elmsln/commit/b435803cf0f67094203f17c98083c506077bb256

https://github.com/elmsln/elmsln/commit/aabb7d1a8894dd4c11de6b936cc807e5b4c6da5c

https://github.com/elmsln/elmsln/commit/90be593397e4ad9885f6b13cb7f9a20b580f396f

Appears to have been something in views needing updated

**Comment by JackWillDavis** [comment] 2020-02-21 14:53
I'll try this installer with the drush 8.x-dev version and see if that works, if not I can try adding the views patch. I'll have a think about the installer as well and see if anything comes to mind while I'm in there.

**Comment by JackWillDavis** [comment] 2020-02-21 14:56
I mean Drupal 7.67 and Drush 7.4/8.x have support for PHP 7.2 built in don't they? So do you think it's the installer itself not connecting it up properly on Ubuntu 18?

**Comment by btopro** [comment] 2020-02-21 15:16
so those commits above deal w/ adding support for views; there's something in views that was broken at some point (only for initial install). I feel like it's deprecating notices / contrib support for PHP 7.2+ that's the real issue. Have you checked the logs in trying to do the install afterwards

**Comment by JackWillDavis** [comment] 2020-02-21 15:56
So, there's nothing in the apache error logs apart from messages when apache is restarting. The INSTALL-LOG.txt in config gets deleted but I think just lists out the steps it gets up to (installing the interact authority tool).

Nothing in the php-fpm logs either. When running it a second time I get a load of MySQL errors for not being able to create users/databases (this is because the root MySQL password is discarded through the install process isn't it?).  This throws Drush bootstrap issues.

The errors all seem to be when it reaches the point of firing the `drush site-install` commands. I get a couple like below:

(This this is fired on composer install actually)
![image](https://user-images.githubusercontent.com/2301874/75049300-e1af3a00-54c1-11ea-9cdc-930241a6a199.png)

![image](https://user-images.githubusercontent.com/2301874/75049366-f8559100-54c1-11ea-9b0b-25364c78b647.png)

![image](https://user-images.githubusercontent.com/2301874/75049449-1cb16d80-54c2-11ea-826a-a8045d2c39e2.png)

I'm officially stumped. I've updated the dependencies and written in a new section in `elmsln-install.sh` which accounts for Ubuntu18 and connects up PHP 7.2. The only thing I've really got to go on at this point is that the `drush version` doesn't work until you close the terminal down which shouldn't be the case with `source ~/.bashrc`.

**Comment by btopro** [comment] 2020-02-21 16:10
what happens if you try to install a site via drush manually? It sounds like an issue of drush and php versions some how

**Comment by JackWillDavis** [comment] 2020-02-21 16:13
I get the bootstrapping error if I run `drush site-install` manually as it doesn't have the db credentials to access the site. There is no DB config inside settings.php files for the stacks either because the initial install doesn't go through.

**Comment by btopro** [comment] 2020-02-21 16:15
what of the generic php logs as opposed to fpm specific ones and if you go to like a generic index.php page via URL does it actually process the PHP? Looking for an interplay issue between Apache and PHP / PHPfpm mayhaps.

The DB errors on reinstall make sense because mysql is installing SOMETHING (which suggests to me there might be PHP level errors bc of contrib compatibility)

**Comment by JackWillDavis** [comment] 2020-02-21 16:53
I get a 500 error if I go to the page after running the installer, although it does redirect me to the install.php file. 

Here's the log for when I try and access the page:

Uncaught Error: Call to undefined function db_query() in /var/www/elmsln/core/dslmcode/cores/drupal-7/includes/cache.inc:359

Apart from that, nothing is getting logged, just seems to be printing into the terminal.

**Comment by btopro** [comment] 2020-02-21 17:06
well that attempt so php is at least there. Where are you looking for the php errors and is this being run as root?

**Comment by JackWillDavis** [comment] 2020-02-21 17:16
AFK at the moment but it’s being run as user `Ubuntu` as it’s a Lightsail instance. I’m looking in `/var/log` and `/etc/php/7.2/` for logs.

**Comment by btopro** [comment] 2020-02-21 17:20
I have no idea how something that's clearly throwing error in php and not installing is some how not logging said errors. are you able to install a vanilla drupal site on the server in any other directory that is web available? This might help us figure out if the issue is server config or something in contrib stuff needing updated. Also did you update views before running install (it legit bricks the install without that fix).

**Comment by JackWillDavis** [comment] 2020-02-21 17:26
The views fix needs to be put in place before installing? I didn’t get a chance to test that, was it throwing the same bootstrap error on your end before it was patched?

**Comment by JackWillDavis** [comment] 2020-02-21 17:26
And I’ll try out a vanilla Drupal install

**Comment by btopro** [comment] 2020-02-21 17:28
yes, has to be in before installing. I think I'm going to merge the es8 branch into the 13.x and then we have a "next" branch to work against. Not all the visual assets are working / tested in the es8 branch but it's the furthest ahead w/ backend changes. Let me see if a PR will resolve easily.

**Comment by btopro** [comment] 2020-02-21 17:31
ok, let's try this as steps (I just merged ES8 into 0.13.x).

- new server to install on
- pull the 0.13.x code
- try the install

if it fails, THEN do the vanilla drupal install and let's see if this is server config or code in nature. Also whatever things you've corrected in your setup keep those things.

**Comment by JackWillDavis** [comment] 2020-02-24 15:59
OK, so I wasn't able to get it installed using the new 0.13.x branch unfortunately.

I've just gone through and set up a LAMP stack on a bare Ubuntu18 server and tried to install base Drupal 7.67. It seems mariadb is rejecting logins from Drupal (even though I'm able to login via the command line using the same credentials).

![image](https://user-images.githubusercontent.com/2301874/75168221-731ae800-571e-11ea-89ff-6d3b03e05acd.png)

It would explain the bootstrapping/db issues if mariadb doesn't support U18 but have you ever seen this before?

**Comment by JackWillDavis** [comment] 2020-02-24 16:05
Ignore previous comment, yeah I can install base Drupal 7.67 on Ubuntu 18 with PHP 7.2.

**Comment by JackWillDavis** [comment] 2020-02-24 16:33
I am seeing this now though, a mariaDB error message:

![image](https://user-images.githubusercontent.com/2301874/75171270-45846d80-5723-11ea-87b2-f9fa4dcdaeb0.png)

Happens on every site and then the bootstrapping issue appears afterwards.

**Comment by btopro** [comment] 2020-02-24 16:38
hmm... MariaDB syntax error maybe there's something in the files we use for settings.php that causes this?! (to confirm your frustration, this still pisses me off bc we don't modify anything to do with installation in probably 2 years if not more).

**Comment by JackWillDavis** [comment] 2020-02-24 17:08
I guess Ubuntu 18 has a different mariadb-server requirement which we need to meet? Where would you recommend starting to look? I can see `configpwd.cfg` has apostrophes in the file, is it a case of it's pulling out the apostrophe and trying to insert that into the db as well?

So, I guess the main issue is [here](https://github.com/elmsln/elmsln/blob/master/scripts/install/elmsln-install.sh#L121) and [here](https://github.com/elmsln/elmsln/blob/master/scripts/install/elmsln-install.sh#L140)? Or at least in the password it's passing through?

**Comment by btopro** [comment] 2020-02-24 18:51
Have you tried running those but replacing the variables w/ their actual setting? I don't see why apostrophes would be an issue but I haven't installed on Maria before @bradallenfisher any issues in the past w/ install scripts and maria in this way?

**Comment by btopro** [comment] 2020-03-24 04:10
0.13.x just updated core and a lot of contrib for PHP 7.2+ compatibility so this hopefully helps here as well though untested.

**Comment by JackWillDavis** [comment] 2020-03-24 10:14
Yeah just finishing up a couple of other jobs first but hoping to get back to this fairly soon. Will give it a few run throughs when I can

**Comment by btopro** [comment] 2020-03-31 12:26
0.13.x was merged into master and tagged as 1.0.0. I've still got some improvements to the ubuntu 18 installer beyond where it was and am trying to get travis working again so we can analyze that for build issues once again. There were a lot of pre-flight dependency checks that were busted, now fixed. I'll keep checking in on it and trying to resolve stuff as it gets further but whenever you get back to this try master

**Comment by JackWillDavis** [comment] 2020-10-21 15:25
Hi, just back on this. I've tried an installer using v1.0.6 and it's mostly working, I've got a couple of tweaks which I'm storing here: https://github.com/JackWillDavis/elmsln/commits/ubuntu18

There are a couple of issues I just wanted to run by you though as I can't see an easy fix to put in.

The first is an issue with the URL which is being passed to `_cis_connector_url_get_properties()`, I'm getting the following error on quite a few of the `site-install` steps during the latter part of the installation:

![image](https://user-images.githubusercontent.com/2301874/96740701-faf1e880-13b8-11eb-8ed8-2d7b769797d4.png)

I'm also getting a weird issue where the admin user isn't being granted the `administrator` role on installation which I think is related to this error message:

![image](https://user-images.githubusercontent.com/2301874/96741070-591ecb80-13b9-11eb-97c5-cb4678947b93.png)

I'm also getting quite a few of these messages too although I can't tell what impact it's having:

![image](https://user-images.githubusercontent.com/2301874/96741244-810e2f00-13b9-11eb-92ac-148d359f03ed.png)

There's also no theme set on the front-end when first navigating to the front of a fresh install. I get a message about `cis_foundation_access` missing from the filesystem. Just wanted to check with you first on that one as I'm not sure if you removed the theme setup as I know you're on with decoupling.

I'm working on a fresh Ubuntu 18.04 (PHP 7.2) server at the moment so none of our customisations are included in the installation at this point.

**Comment by btopro** [comment] 2020-10-21 17:01
_cis_connector_url_get_properties fixed and the admin account aspect has a "fix" pushed up into the install; hopefully these help resolve those ones. No idea on the field collections thing. Looks related to views in that last notice. cis_foundation_access might imply that the install profile is not actually set correctly to cis. `drush @online vget install_profile` and see if that returns the cis value. Could also be a 1x cache thing.

Good to see your narrowing in.

**Comment by JackWillDavis** [comment] 2020-10-22 09:09
Thanks a lot, I'll give the new stuff a go this morning. I ran that drush command and got a `No matching variable found.` message back so think you're right there about cis.

**Comment by JackWillDavis** [comment] 2020-10-22 14:22
Hi,

So I've given this a few more goes. Definitely a profile issue with CIS and I'm hoping the other issues are just branching off from that. I've checked the `elmsln-install.sh` file and it's definitely correctly defining CIS as the profile for Online.

I noticed there was a potential issue with the symlink for the CIS profile which I've adjusted [here](https://github.com/JackWillDavis/elmsln/commit/e75aef94905ec11fb9863b1072423cc8e86dc097) to bring it in line with the other profiles. Unfortunately, I'm still getting the same issues where the CIS profile isn't being installed for online but they are being installed correctly for the other authority sites.

**Comment by JackWillDavis** [comment] 2020-10-22 14:36
Just an update, I can access CIS when I use the profile switcher module and manually set it to `cis`.

**Comment by btopro** [comment] 2020-10-22 17:53
symlink not a bad thing to adjust. I wonder if we need another step or something in spin up. There's no reason it shouldn't be finding the installer as nothing has changed there. if you can switch to cis that means that the file system is there correctly. I wonder if you can install CIS by doing a `drush si` as opposed to doing the manual profile setting to cis? Maybe there's something borked in CIS on install failing silently. Views has been able to cause this in the past

**Closed** 2020-10-23 17:33 UTC
