### ISSUE TITLE
HTML comments in wysiwyg cut off content further down

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#2302] opened 2017-10-18 11:35 UTC
Bug:
- v0.8.1

- Our content outline is full of HTML comments where we signal to beginning/end of different style templates/components. It looks like wherever a comment is inserted - the content below this doesn't show on the wysiwyg

**View on the page:**
![image](https://user-images.githubusercontent.com/4973810/31716532-34a6b400-b400-11e7-9ac1-fb1e863e2ce9.png)

**WYSIWYG**
![image](https://user-images.githubusercontent.com/4973810/31716565-60495982-b400-11e7-9822-6731c2ae2c67.png)

**Source Code**
![image](https://user-images.githubusercontent.com/4973810/31716597-87e68bd6-b400-11e7-8618-53ddea1c59f7.png)

**Comment by btopro** [comment] 2017-10-18 12:12
that's weird.... have you tried placing the comment after the closing </p> there. Also maybe see if the "correct faulty HTML" option is in the input filters `admin/config/content/formats/textbook_editor`

It's on by default and might be misidentifying this text and "correcting" it

**Comment by rickhumphries** [comment] 2017-10-18 13:42
Placing a comment after the closing...? I've switched off that option in the input filters but it didn't have an affect. 

I also deleted all the comments from the source to make sure that it was definitely them causing it, and deleting them makes everything appear in the wysiwyg - so pretty certain it's that.

**Comment by btopro** [comment] 2017-10-18 13:52
the comment is within a <p> tag; what if it's by itself like not in a tag does that help at all?

**Comment by rickhumphries** [comment] 2017-10-18 14:51
No that doesn't seem to do it. I'm trying to figure out a pattern to it but can't...It's definitely trying to process it in some way though, even with the 'correct faulty HTML' option switched off

**Comment by btopro** [comment] 2017-10-18 15:07
does it display while in CKEditor?

**Comment by rickhumphries** [comment] 2017-10-18 15:16
No,  so the WYSIWYG view show above is the view I get in CKEditor. 

It's almost as if the CKEditor view isn't recognising the closing comment tag or something so is just cutting it off.

I also notice that if I keep switching between source and view mode in CKEditor, it keeps adding paragraph tags after the closing comment -->

**Comment by rickhumphries** [comment] 2017-10-18 15:23
...but it only does that with some comments, not others. urgh

**Comment by btopro** [comment] 2017-10-18 15:26
there's some additional wysiwyg clean up in 0.9.0 for webcomponents so it doesn't do that weird <p> tag addition thing u mention. This happens when ckeditor doesn't know what the tag is (it's behavior that seems intentional for some reason).

https://forums.cubecart.com/topic/52120-ckeditor-deletes-comment-tags-in-product-description/

might help

**Comment by rickhumphries** [comment] 2017-10-18 15:29
It's just strange cause it doesn't do this in our 0.7.0 instance that's currently live. Is there any way of checking if anything was changed with regard to this between 0.7.0 and 0.8.0?

**Comment by rickhumphries** [comment] 2017-10-18 15:33
Thanks for the link too, but that seems to be about the html comment being deleted. Whereas in this case the comment remains - but seems to be effecting ONLY the CKEditor view - not the rendered view when saved

**Comment by rickhumphries** [comment] 2017-10-18 16:44
Inspecting difference between 0.7.0 and 0.8.1

**0.7.0**
![image](https://user-images.githubusercontent.com/4973810/31730999-987db160-b42b-11e7-8b26-69f118175fa7.png)

**0.8.1**
![image](https://user-images.githubusercontent.com/4973810/31731019-a4fb9074-b42b-11e7-9a87-346d0d7f4e6f.png)

It seems like when it's being compiled in 0.8.1, CKEditor isn't recognising the closing tag properly.

**Comment by btopro** [comment] 2017-10-18 19:00
hmm... ckeditor hasn't been updated since early 2016 so I'm not sure that anything was done to it specifically from looking through commit logs

**Comment by rickhumphries** [comment] 2017-10-19 08:14
Tried replacing `<!-- COMMENT -->` with `<script>/* COMMENT */</script> and that's _kind of_ better but still throwing some funny behaviour too.

Hmm, I'm a bit desperate to find a solution to this because it's going to ruin our course authoring process otherwise. Will keep looking

**Comment by JackWillDavis** [comment] 2017-10-19 09:55
Hi @btopro, please could you tell me where the CKEditor settings are configured from? I can find dozens of CKEditor config files throughout ELMSLN but I can't seem to get any of them to reflect any changes on the course edit page at (for example): courses.elms-dev.com/jacktestco/node/92/edit

**Comment by JackWillDavis** [comment] 2017-10-19 11:18
Just a quick update: I found the admin section in ELMSLN where you can configure text formats and editors but it's not playing along. For some reason, it is not seeing the closing HTML comment tag and so it is being placed right to end of the WYSIWYG preview, which of course hides everything.

Still not sure about where the settings are kept, how would I go about installing CKEditor plugins?

**Comment by btopro** [comment] 2017-10-19 11:32
https://github.com/elmsln/elmsln/blob/master/core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/ckeditor_custom_config.js

**Comment by btopro** [comment] 2017-10-19 11:33
wild guess but I've seen `config.protectedSource.push` syntax which maybe would add more things to the protected set where as I apparently am setting it to just  `config.protectedSource = [/<(\S*?)-(\S*?)\s*>[\s\S]*?<\/(\S*?)-(\S*?)>/g];`

**Comment by btopro** [comment] 2017-10-19 11:44
![2017-10-19_07-43-47](https://user-images.githubusercontent.com/329735/31769359-415851a8-b4a1-11e7-9832-552a1db4f3bf.png)

Not able to reproduce, do u have a sample block of text that is bombing on this and I can try to cross reference from there

**Comment by rickhumphries** [comment] 2017-10-19 12:02
@btopro So that looks normal in the WYSIWYG view if you come out of the source code?

**Comment by JackWillDavis** [comment] 2017-10-19 12:04
![image](https://user-images.githubusercontent.com/2301874/31769904-665face0-b4cd-11e7-9d9a-80df1ccfd848.png)

Here is one of the blocks which is causing the issue. The first opening comment tag is replaced with:

![image](https://user-images.githubusercontent.com/2301874/31769961-9e833164-b4cd-11e7-9ae7-4417da492d1e.png)

when switching to the WYSIWYG window. The Source view looks totally fine it is just messing up when it gets switched to the WYSIWYG pane.

I did try that custom ckeditor config file in the theme but when I tested it by trying to add a new colour to the Highlight button on the editor, it didn't show up so I assumed it was somewhere else.

**Comment by btopro** [comment] 2017-10-19 12:45
Ya I hit save and it retains it when I come back to it

On Oct 19, 2017 8:02 AM, Rick Humphries <notifications@github.com> wrote:

@btopro<https://github.com/btopro> So that looks normal in the WYSIWYG view if you come out of the source code?

**Comment by rickhumphries** [comment] 2017-10-19 12:50
It's not when you hit save that's the issue - it's switching between source view and wysiwyg view (whilst still in edit mode)

**Comment by btopro** [comment] 2017-10-19 13:38
Also wasn't an issue in my test but I'll look more tonight

On Oct 19, 2017 8:50 AM, Rick Humphries <notifications@github.com> wrote:

It's not when you hit save that's the issue - it's switching between source view and wysiwyg view (whilst still in edit mode)

**Comment by rickhumphries** [comment] 2017-10-19 13:40
OK no worries - thanks

**Comment by btopro** [comment] 2017-10-19 16:25
May need to clear local cache and drupal cache to see it. Ckeditor is aggressive w. Local storage to cheat on some settings delivery I've noticed

On Oct 19, 2017 8:04 AM, Jack Davis <notifications@github.com> wrote:

[image]<https://user-images.githubusercontent.com/2301874/31769904-665face0-b4cd-11e7-9d9a-80df1ccfd848.png>

Here is one of the blocks which is causing the issue. The first opening comment tag is replaced with:

[image]<https://user-images.githubusercontent.com/2301874/31769961-9e833164-b4cd-11e7-9ae7-4417da492d1e.png>

when switching to the WYSIWYG window. The Source view looks totally fine it is just messing up when it gets switched to the WYSIWYG pane.

I did try that custom ckeditor config file in the theme but when I tested it by trying to add a new colour to the Highlight button on the editor, it didn't show up so I assumed it was somewhere else.

**Comment by JackWillDavis** [comment] 2017-10-20 09:35
OK, I was being daft and not clearing my cache from more than an hour previously which was obviously keeping the CKEditor stuff. I can see changes being made from the ckeditor_custom_config.js file now thanks. I have fixed our issue by removing the protected source regex line.

Please could you tell me if this is advisable? Or is it being used for other things and I'd be best adapting it to exclude HTML comments instead?

**Comment by btopro** [comment] 2017-10-20 12:05
It helps with allowing custom elements but if you arn't doing that yet don't worry about it. Maybe let's amend the title of this one to be about the fact that the regex needs adjusted to accept comment tags and protect them.

It's also possible I need to add my regex ibated of overwrite it like it presently is doing. Glad you found a fix for now

On Oct 20, 2017 5:36 AM, Jack Davis <notifications@github.com> wrote:

OK, I was being daft and not clearing my cache from more than an hour previously which was obviously keeping the CKEditor stuff. I can see changes being made from the ckeditor_custom_config.js file now thanks. I have fixed our issue by removing the protected source regex line.

Please could you tell me if this is advisable? Or is it being used for other things and I'd be best adapting it to exclude HTML comments instead?

**Comment by JackWillDavis** [comment] 2017-10-20 15:26
Just for reference, I was able to get around this by adjusting the rule from:

config.protectedSource = [/<(\S*?)-(\S*?)\s*>[\s\S]*?<\/(\S*?)-(\S*?)>/g];

to:

config.protectedSource = [<(!-{2,}|(\S*?)-(\S*?)\s*>)[\s\S]*?(<\/(\S*?)-(\S*?)|(-{2,}))>/g];

This _should_ include HTML comments properly within the protected range as well as anything originally intended.

**Comment by JackWillDavis** [comment] 2017-10-20 15:29
Just for reference I was able to get around this by adjusting the regex to:

config.protectedSource = [<(!-{2,}|(\S*?)-(\S*?)\s*>)[\s\S]*?(<\/(\S*?)-(\S*?)|(-{2,}))>/g];

Not sure if it is suitable for ELMSLN though as you weren't seeing the same issue as us...

**Comment by btopro** [comment] 2017-10-21 02:03
well, if u can put in a web component and it still work then this sounds like a good PR for testing since we want to support this.

Try putting this in the body field and do your source / no source clicking a bunch then save and see if it shows up still: `<elmsln-loading>` if that doens't do anything (forget what version that came in off the top of my head) try `<lrn-icon icon="network"></lrn-icon>` and see if that renders.

The regex was meant to prevent CKEditor from removing webcomponents as it would normally get annoyed that they "aren't real tags"

**Comment by JackWillDavis** [comment] 2017-10-23 08:15
Just tested it with `<p>Test: <lrn-icon icon="network"></lrn-icon></p>` and it saves it correctly; CKEditor doesn't remove it :)

**Comment by JackWillDavis** [comment] 2017-10-23 08:30
Let me know if you'd like me to put through a PR and whether it would be best for the 0.8.1 branch or master.

**Comment by btopro** [comment] 2017-10-23 13:55
PR should be against 0.10.x; you'll want to just patch this manually on yours knowing its fixed in the future releases

**Comment by btopro** [comment] 2017-10-23 16:26
fixed via PR

**Closed by btopro** 2017-10-23 16:26 UTC
Labels: bug
