### ISSUE TITLE
Course schedule setup tool

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#311] opened 2015-10-30 02:05 UTC
Related the Calendar #310, there needs to be a super fast way to build the course schedule out. We'll need an interactive step-by-step form of some kind to handle this.

**Comment by btopro** [comment] 2016-01-31 23:09
@curiosity26 @kat-wehr should talk to Collins about the Syllabus builder thing we talked about the other day; may be related

**Comment by curiosity26** [comment] 2016-01-31 23:21
Cool! Let's set something up this week
On Sun, Jan 31, 2016 at 6:09 PM Bryan Ollendyke <notifications@github.com>
wrote:

> @curiosity26 <https://github.com/curiosity26> @kat-wehr
> <https://github.com/kat-wehr> should talk to Collins about the Syllabus
> builder thing we talked about the other day; may be related
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elmsln/elmsln/issues/311#issuecomment-177653887>.
>
-- 
Alex Boyce

**Comment by btopro** [comment] 2016-11-30 06:36
duplicate of #1051 #310 #842 #935

**Closed by btopro** 2016-11-30 06:36 UTC
Labels: enhancement, Instructor Experience, Staff Experience, Tool to build, User Experience
