### ISSUE TITLE
Gitbook imports duplicates

### ISSUE THREAD

**Issue by michael-collins** [elmsln/elmsln#2171] opened 2017-08-22 16:47 UTC
<img width="1157" alt="screen shot 2017-08-22 at 12 46 09 pm" src="https://user-images.githubusercontent.com/1085304/29577038-feca08f4-8737-11e7-98ed-c15348d7fd9f.png">

**Comment by btopro** [comment] 2017-08-22 18:50
This is the git import

**Comment by heyMP** [comment] 2017-08-22 18:52
From Slack:

yeah, I don’t know why that’s happening.  it’s possible that it has something to do with line endings within the summary file but I haven’t had a chance to debug it.

The work around right now is to delete the book and recreate it.

or better yet, if you are able to easily delete all of the pages within the book then re-sync it with `git-book-sync` that would be better.

**Comment by btopro** [comment] 2017-08-23 19:29
specific instance fixed but this is still a bug when sycning

**Comment by btopro** [comment] 2018-02-26 21:27
duplicate of this issue (since it's actually a sync issue)

**Closed by btopro** 2018-02-26 21:27 UTC
Labels: bug, courses / mooc, git / markdown ingestion
