### ISSUE TITLE
Contexual Links on Media assets missing

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#2476] opened 2018-06-09 14:19 UTC
I'm not sure if this is a bug or if we decided to move in a different direction.  The usual contextual links that appear on media items loaded via tokens do not appear.  Users reported not knowing how to edit existing media items without them.

![screen shot 2018-06-09 at 9 58 32 am](https://user-images.githubusercontent.com/3428964/41192610-5e5d77ee-6bce-11e8-8409-deb6593555fd.png)

**Comment by btopro** [comment] 2018-06-25 23:20
related issue that HAX will help in solving -- https://github.com/LRNWebComponents/hax-body/issues/144

**Comment by btopro** [comment] 2018-06-26 02:47
desired workflow
- hit edit to go into HAX mode
- click item, hit edit gear
- present cms-tag hax settings, running postProcessgetHaxJSONSchema to provide a quick link to elmsmedia
- pop up in new window directly to edit form of that item (specialized page tho)
- on save, close window and trigger an event to refresh the cms-token being displayed.

**Comment by btopro** [comment] 2018-06-26 21:02
https://www.youtube.com/watch?v=j1gpkrloTN0 !!!!!!!!!!!!!!! @rickhumphries

**Comment by btopro** [comment] 2018-06-27 02:06
No longer marking this as a bug, now it is by design (new tag). This is because the new HAX + cms-tokens + instant refreshing and updating media system workflow (even in it's current state) beats the pants off of the old method. #264 is now on by default for staff and admins as of the latest 0.10.x

**Closed by btopro** 2018-06-27 02:06 UTC
Labels: by design, courses / mooc, media / elmsmedia
