### ISSUE TITLE
External Video has margin issues

### ISSUE THREAD

**Issue by heyMP** [elmsln/elmsln#682] opened 2016-02-26 21:29 UTC
![screen shot 2016-02-26 at 4 19 56 pm](https://cloud.githubusercontent.com/assets/3428964/13365954/1b5e3974-dca6-11e5-84bd-275ffdb763ac.png)

**Comment by btopro** [comment] 2016-02-27 22:47
related #170

**Comment by btopro** [comment] 2016-06-18 13:59
duplicate of #170

**Closed by btopro** 2016-06-18 13:59 UTC
Labels: bug, easy, medium, style guide / theme
